name: mypy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --with dev
    - name: Run mypy
      run: |
        make mypy
